openapi: 3.0.3
info:
  title: csb-server
  description: |-
    csb-server api spec an Webhook test
  version: 0.0.1
servers:
  - url: "http://localhost:8080"
  - url: "https://microcks-microcks.apps.cluster-56dmd.56dmd.sandbox2864.opentlc.com/rest/csb-server/0.0.1"
paths: {}
